### ISSUE TITLE
teardown?

### ISSUE THREAD

**Issue by technion** [epgsql/pgapp#11]
Hi,

I'm wondering if there's a way to "stop" a simple pool? I have eunit fixtures which need to setup pgapp:connect/1, and then tear it down before the next function call. Without the teardown, I'm just getting crashes with:

```erlang
** exception error: no match of right hand side value
                    {error,{already_started,<0.188.0>}}
```

If you can advise regarding this it would be appreciated.

**Comment by davidw** [comment]
No, there isn't.  It sounds like it might be a valuable addition.

**Comment by technion** [comment]
Thanks for the confirm, may work on this feature at some point.
